# Generated by Django 4.0.4 on 2022-06-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_usuario_delete_ciudadano_remove_desecho_reciclable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantIntegrantes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Superhumano',
            fields=[
                ('nombre', models.CharField(max_length=40)),
                ('nivelDePoder', models.IntegerField()),
                ('idSuperhumano', models.IntegerField(primary_key=True, serialize=False)),
                ('esMalvado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Aparicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionLugar', models.CharField(max_length=100)),
                ('superhumano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion.superhumano')),
            ],
        ),
    ]
