# Generated by Django 4.0.4 on 2022-06-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0003_organizacion_superhumano_aparicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparicion',
            name='huboHeridos',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
