# Generated by Django 4.0.4 on 2022-06-07 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0004_aparicion_huboheridos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparicion',
            name='superhumano',
            field=models.CharField(max_length=20),
        ),
    ]
