# Generated by Django 4.0.4 on 2022-06-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0006_delete_desecho_delete_estacion_delete_ticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparicion',
            name='huboHeridos',
        ),
        migrations.RemoveField(
            model_name='superhumano',
            name='esMalvado',
        ),
    ]
